config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists do
    resources :bookmarks, only: [ :new, :create, :update ]
  end
  resources :bookmarks, only: [ :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: "is already in the list" }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_many :reviews
  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list_id = params[:list_id]
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'new'
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to list_path(@bookmark.list_id)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to(@list)
    else
      render 'new'
    end
  end

  private

  def list_params
    params.require(:list).permit(
      :name
    )
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
#   def index
#     @movies = Movie.all
#   end

#   def show
#     @restaurant = Restaurant.find(params[:id])
#   end

#   def new
#     @restaurant = Restaurant.new
#   end

#   def create
#     @restaurant = Restaurant.new(restaurant_params)
#     if @restaurant.save
#       redirect_to restaurant_path(@restaurant)
#     else
#       render 'new'
#     end
#   end

#   private

#   def restaurant_params
#     params.require(:restaurant).permit(
#       :name,
#       :address,
#       :category,
#       :phone_number
#     )
#   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<h1>Add a bookmark</h1>
<%= simple_form_for [ @list, @bookmark ] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit "Create bookmark", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<header style = "height: 50vh;
  min-height: 500px;
  background-image: url('https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1650&q=80');
  background-size: cover;
  background-position: center;
  background-repeat: no-repeat;">
  <div class="container h-100">
    <div class="row h-100 align-items-center">
      <div class="col-12 text-center">
        <h1 class="fw-light" style = "color: white">Cine</h1>
        <p class="lead" style = "color:white">Película en español</p>
      </div>
    </div>
  </div>
</header>


<div class = "container" style = "margin-top: 30px">
  <div class = "row">
    <div class = "col-sm-8">
      <h2>My lists</h2>
    </div>
    <div class = "col-sm-4">
      <%= link_to "Create a list", new_list_path, :class=>"btn btn-primary"   %>
    </div>
  </div>
  <div class = "row">
    <div class="card-deck">
      <% @lists.each do |list| %>
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= link_to list.name, list_path(list)%></h5>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<h1>Create a list</h1>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
    <%= simple_form_for @list do |f| %>
      <%= f.input :name %>
      <%= f.submit class: 'btn btn-primary' %>
    <% end %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<header style = "height: 50vh;
  min-height: 500px;
  background-image: url('https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1650&q=80');
  background-size: cover;
  background-position: center;
  background-repeat: no-repeat;">
  <div class="container h-100">
    <div class="row h-100 align-items-center">
      <div class="col-12 text-center">
        <h1 class="fw-light" style = "color: white"><%= @list.name %></h1>
      </div>
    </div>
  </div>
</header>


<div class = "container" style = "margin-top: 30px; margin-bottom: 30px">
  <div class = "row" style = "margin-bottom: 30px">
    <div class = "col-sm-8">
    </div>
    <div class = "col-sm-4">
      <%= link_to 'Add a bookmark', new_list_bookmark_path(@list), :class=>"btn btn-primary" %>
    </div>
  </div>
  <div class = "row">
    <div class="card-deck">
      <% @list.movies.each do |movie| %>
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"><%= movie.title %></h5>
          <p class="card-text"><%= movie.overview %></p>
          <div class = "container">
            <div class = "row">
              <div class = "col-sm-6">
                <p><i>IDEA: Insert Bookmark comment</i></p>
              </div>
              <div class = "col-sm-6">
                <%= link_to "Remove",
                  bookmark_path(Bookmark.find_by(movie: movie, list: @list)),
                  method: :delete,
                  data: { confirm: "Are you sure?" },
                  :class=>"btn btn-danger"%>
              </div>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>